<?xml version="1.0"?>
<robot name="wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">
 
  <xacro:property name="wheel_offset_x" value="0.7725" />    <!-- x,y,z in base_footprint CS -->
  <xacro:property name="wheel_offset_y" value="0.5025" /> 
  <xacro:property name="wheel_offset_z" value="0.0" /> 
  <xacro:property name="steering_offset_x" value="0.7725" />    <!-- x,y,z in base_footprint CS -->
  <xacro:property name="steering_offset_y" value="0.365" /> 
  <xacro:property name="steering_offset_z" value="0.0" /> 
  <xacro:property name="wheel_to_steering" value="0.11" /> 
  <xacro:property name="wheel_width" value="0.175" /> 
  <xacro:property name="wheel_joint_damping" value="1.0" />
  <xacro:property name="wheel_joint_friction" value="1.0" />
  
  <xacro:property name="hub_dia" value="0.235"/>
  <xacro:property name="tire_dia" value="0.56"/>
  <xacro:property name="tire_width" value="0.2"/>

  <xacro:property name="wheel_mass" value="15.0"/>   <!-- check -->
		

  <!-- Degree-to-radian conversions -->
  <xacro:property name="degrees_45" value="0.785398163"/>
  <xacro:property name="degrees_90" value="1.57079633"/>
  <xacro:property name="degrees_180" value="3.14159265"/>
  <xacro:property name="servo_stall_torque" value="1600"/>  <!-- check -->
  <xacro:property name="servo_no_load_speed" value="25"/> <!-- check -->
  <xacro:property name="wheel_joint_damping" value="0.0"/> <!-- check -->
  <xacro:property name="wheel_joint_friction" value="500.0"/> <!-- check -->

  <!-- axle eff limit = 2 * stall_torque
       as a function of the max gradient (15%) with overall max payload (600Kg) * wheel_radius
       (calculating this way, it should be divided by 2 if 2 motors are used)
       axle_eff_limit = 204.95 / 2 N m = ~102.5 -->
  <!-- xacro:property name="axle_eff_limit" value="102.5"/ -->
  <xacro:property name="axle_eff_limit" value="3200.0"/>
  <!-- max_speed = 33 Km/h = 9.17 m/s
       axle_vel_limit = (2 * pi) * (max_speed / (pi * tire_dia)) =  39.02 rad/s -->
  <xacro:property name="axle_vel_limit" value="39.02"/>


  <!-- The "wheel" macro defines an axle carrier, axle, and wheel. -->
  <xacro:macro name="traction_wheel" params="parent prefix y_reflect x_reflect roll_reflect yaw_reflect x_pos y_pos z_pos x_link_offset y_link_offset z_link_offset">
	
	<link name="${prefix}_wheel_link">
	<inertial>
      <mass value="10" />
      <origin xyz="${x_link_offset} ${y_link_offset} ${z_link_offset}" />
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>    
      <visual>
        <origin xyz="${x_link_offset} ${y_link_offset} ${z_link_offset}"/>
        <geometry>
          <mesh filename="package://robospect_description/meshes/wheels/robospect_wheel_l.dae" scale="1 1 1"/>
          <!--mesh filename="package://robospect_description/meshes/wheels/rbcar_wheel1.stl" scale="1 1 1"/-->
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="${x_link_offset} ${y_link_offset} ${z_link_offset}"/>
        <geometry>
          <mesh filename="package://robospect_description/meshes/wheels/robospect_wheel_l.dae" scale="1 1 1"/>
        </geometry>
      </collision>
    </link>
    
    <joint name="${prefix}_axle_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_reflect * x_pos} ${y_reflect * y_pos} ${z_pos}" rpy="${-roll_reflect * degrees_90} 0 ${yaw_reflect * degrees_180}"/>
      <axis xyz="0 0 ${yaw_reflect}"/>
      <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
      <joint_properties damping="${wheel_joint_damping}" friction="{wheel_joint_friction}"/>
    </joint>
    
    <transmission name="${prefix}_axle_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_axle_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_axle_act">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <gazebo reference="${prefix}_wheel_link">
		<mu1 value="1.0"/> 
		<mu2 value="1.0"/> 
		<fdir1 value="0 0 0"/>
		<kp value="1000000000.0"/> 
		<kd value="1.0" />    
		<material>Gazebo/Grey</material>
    </gazebo>
    
  </xacro:macro>
  
  <xacro:macro name="steering_wheel" params="parent prefix y_reflect x_reflect roll_reflect yaw_reflect x_pos y_pos z_pos">
	
	<link name="${prefix}_steering_link">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0"/>
			<inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
		</inertial>
    </link>
    
    <joint name="${prefix}_steering_joint" type="revolute">
	  <origin xyz="${x_reflect * x_pos} ${y_reflect * y_pos} ${z_pos}"/>
      <parent link="${parent}"/>
      <child link="${prefix}_steering_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-degrees_45}" upper="${degrees_45}"
             effort="${servo_stall_torque}" velocity="${servo_no_load_speed}"/>
             
    </joint>
    
    <transmission name="${prefix}_steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_steering_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_steering_act">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <gazebo reference="${prefix}_steering_link">
    </gazebo>
   
    <xacro:traction_wheel prefix="${prefix}" parent="${prefix}_steering_link" x_reflect="0" y_reflect="${y_reflect}" yaw_reflect="${yaw_reflect}" roll_reflect="${roll_reflect}" x_pos="0.0" y_pos="${wheel_to_steering}" z_pos="0.0" x_link_offset="0.0" y_link_offset="0.0" z_link_offset="${-wheel_width/2.0}"/>
        
  </xacro:macro>
  
  <xacro:macro name="steering_center_wheel" params="parent prefix y_reflect x_reflect roll_reflect yaw_reflect x_pos y_pos z_pos">
	
	<link name="${prefix}_steering_link">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0"/>
			<inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
		</inertial>
    </link>
    
    <joint name="${prefix}_steering_joint" type="revolute">
	  <origin xyz="${x_reflect * x_pos} ${y_reflect * y_pos} ${z_pos}"/>
      <parent link="${parent}"/>
      <child link="${prefix}_steering_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-degrees_45}" upper="${degrees_45}"
             effort="${servo_stall_torque}" velocity="${servo_no_load_speed}"/>
             
    </joint>
    
    <transmission name="${prefix}_steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_steering_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_steering_act">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

   
        
  </xacro:macro>
  
  <xacro:macro name="wheels"
               params="parent">
    
    <xacro:traction_wheel prefix="left_front" parent="${parent}" x_reflect="1" y_reflect="1" yaw_reflect="1" roll_reflect="1" x_pos="${wheel_offset_x}" y_pos="${wheel_offset_y}" z_pos="0.0" x_link_offset="0.0" y_link_offset="0.0" z_link_offset="${-wheel_width/2.0}"/>
    <xacro:traction_wheel prefix="right_front" parent="${parent}" x_reflect="1" y_reflect="-1" yaw_reflect="-1" roll_reflect="-1" x_pos="${wheel_offset_x}" y_pos="${wheel_offset_y}" z_pos="0.0" x_link_offset="0.0" y_link_offset="0.0" z_link_offset="${-wheel_width/2.0}"/>
    
    <xacro:steering_wheel prefix="left_rear" parent="${parent}" x_reflect="-1" y_reflect="1" yaw_reflect="1" roll_reflect="1" x_pos="${steering_offset_x}" y_pos="${steering_offset_y}" z_pos="0.0"/>
    <xacro:steering_wheel prefix="right_rear" parent="${parent}" x_reflect="-1" y_reflect="-1" yaw_reflect="-1" roll_reflect="-1" x_pos="${steering_offset_x}" y_pos="${steering_offset_y}" z_pos="0.0"/>
    
    <xacro:steering_center_wheel prefix="center_rear" parent="${parent}" x_reflect="-1" y_reflect="-1" yaw_reflect="-1" roll_reflect="-1" x_pos="${steering_offset_x}" y_pos="0.0" z_pos="0.0"/>
    
    
  </xacro:macro>
 <!-- 
 <link name="${lr_prefix}_steering_link">
    </link>

    <joint name="${lr_prefix}_steering_joint" type="revolute">
      <parent link="${lr_prefix}_steering_link"/>
      <child link="${lr_prefix}_${fr_prefix}_axle_carrier"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-degrees_45}" upper="${degrees_45}"
             effort="${servo_stall_torque}" velocity="${servo_no_load_speed}"/>
    </joint>
    
    <transmission name="${lr_prefix}_steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr_prefix}_steering_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr_prefix}_steering_act">

        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <gazebo reference="${lr_prefix}_steering_link">
      <material>Gazebo/Grey</material>
    </gazebo>
    -->

 </robot>
